//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicWpfApp.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolyclinicDBEntities : DbContext
    {
        private static PolyclinicDBEntities _context;

        public static PolyclinicDBEntities GetContext()
        {
            if( _context == null )
                _context = new PolyclinicDBEntities();
            return _context;
        }


        public PolyclinicDBEntities()
            : base("name=PolyclinicDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmissionTicket> AdmissionTicket { get; set; }
        public virtual DbSet<DoctorsPosition> DoctorsPosition { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<TicketState> TicketState { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
