//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicWpfApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsPosition
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> positionId { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual User User { get; set; }
    }
}
