//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicWpfApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> cabinet { get; set; }
        public Nullable<System.DateTime> timeStart { get; set; }
        public Nullable<System.DateTime> timeEnd { get; set; }
        public System.TimeSpan appointmentTime { get; set; }
        public Nullable<int> positionId { get; set; }

        public string appointmentTimeToString
        {
            get
            {
                return this.appointmentTime.Minutes.ToString();
            }
        }

        public DateTime ShortDate
        {
            get
            {
                DateTime shortDate = (DateTime)timeStart;
                return shortDate.Date;
            }
        }

        public virtual Position Position { get; set; }
        public virtual User User { get; set; }
    }
}
